name: speed_ball_run
description: "A goal-tracking app with timers."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^8.0.1
  go_router: ^17.1.0
  intl: ^0.20.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.6.3
  build_runner: ^2.11.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
